### ISSUE TITLE
PA Review: Hosting on Heroku

### ISSUE THREAD

**Issue by Ian-MacLeod** [Ian-MacLeod/sound-macleod#2]
## Initial Deployment:
- [x] Initial push to heroku

## Final Deployment:
- [x] Remove console statements: debuggers, console.logs, errors, minification warnings, mixed content warnings
- [x] Use dev tools in dev environment

## Bonus:
- [ ] Custom domain name

**Comment by anastassia-b** [comment]
Nice! https://sound-macleod.herokuapp.com/#/

**Comment by anastassia-b** [comment]
Excellent. I also love how you designed the splash page!
