### ISSUE TITLE
PA Review: User Authentication

### ISSUE THREAD

**Issue by Ian-MacLeod** [Ian-MacLeod/sound-macleod#3]
- [x] Backend: DB, model, controller, views
- [x] Redux Loop: ajax, actions, reducer
- [x] Presentational Components
- [x] Styling
- [x] Smooth, bug-free navigation
- [x] Adequate and appropriate seeds

**Comment by anastassia-b** [comment]
Hey @Ian-MacLeod , great work! The functionality is great- I can login, logout, and signup. Styling is great too! 

A few small things to complete this MVP:
- [x] Add a "demo login" option
- [x] Clear errors when a user toggles between login and signup forms

**Comment by anastassia-b** [comment]
Awesome, this MVP is complete.
