### ISSUE TITLE
PA Review: Production README.md

### ISSUE THREAD

**Issue by Ian-MacLeod** [Ian-MacLeod/sound-macleod#8]
- [x] Create Production README

**Comment by anastassia-b** [comment]
**Content:**
- [x] Has a `# Title`
- [x] Links to the Wiki design documents
- [x] Describes technologies used
- [x] Describes core functionality
- [x] Lists future directions
- [x] Fills out `Description` and `Website` at the top of the repo.

**Format:**
- [x] Uses markdown formatting
- [x] Includes code snippets (with triple backticks, and the language ` ```javascript...``` `)
- [x] Includes screenshots / gifs

**Optional:**
- [x] Describes technical challenges
- [ ] Add `topics` to the top of the repo

**Comment by anastassia-b** [comment]
Great work on the entire thing!
